### ISSUE TITLE
Add a way to see the number of unknown morphs on a note

### ISSUE THREAD

**Issue by buster-blue** [mortii/anki-morphs#92] opened 2023-12-09 21:02 UTC
**Is your feature request related to a problem? Please describe.**
I like to see how close a note is to being ready. It helps to give me motivation when I see more and more cards start to have lower unknown counts, and it lets me know how close I am to being able to learn specific notes.

**Describe the solution you'd like**
Add an optional field in the "Extra Fields" section that's similar to the one Morphman has. Maybe call it something like "AM_unknown_count". If not that, then add some other way of seeing the number of unknown morphs on a note.

**Describe alternatives you've considered**
N/A

**Additional context**
Morphman has a field for this, and I liked it.

**Comment by Vilhelm-Ian** [comment] 2023-12-09 21:05
@buster-blue  what is the use case for this?

**Comment by buster-blue** [comment] 2023-12-09 21:52
@Vilhelm-Ian 
> It helps to give me motivation when I see more and more cards start to have lower unknown counts, and it lets me know how close I am to being able to learn specific notes.

It also acts as a casual way to see if the notes I added for a certain source have a lot of words I don't know. But it's mostly that it feels nice to see the progress on an individual note that has many unknowns. It was cool to see this info in Morphman.

**Comment by Vilhelm-Ian** [comment] 2023-12-09 21:58
> It also acts as a casual way to see if the notes I added for a certain source have a lot of words I don't know. 

You will be able to do that much easier using the upcoming readabliity analyzer feature(morphman has one). 

Also for the motivation part. I get I also liked seeing unknown morphs part on the readability analyzer go down.

I just don't think there is a valid reason to add this feature.

**Comment by buster-blue** [comment] 2023-12-09 22:56
> You will be able to do that much easier using the upcoming readabliity analyzer feature(morphman has one).

I don't want to see the readability of some text file that I have on my desktop. I never used the readability analyzer in Morphman. I want to see how close a note is to being ready, by seeing how many unknown morphs it has, and to be able to sort all the notes by how many unknowns they have to compare using field sorting. If those aren't considered valid enough reasons, then I'll accept that, but the readability analyzer isn't going to do what I want here, so it's not a solution for me.

**Comment by Vilhelm-Ian** [comment] 2023-12-09 23:01
You want to get the motivation kick of knowing you are getting closer to understand a piece of media. 

With the readability analyzer you can see how the number of unknown morphs is decreasing for a piece of media without having to check individual notes. 

This project is mortii work. It all depends if he wants to implement it.

**Comment by buster-blue** [comment] 2023-12-09 23:13
> You want to get the motivation kick of knowing you are getting closer to understand a piece of media.

No. I want to know how close I am to being able to learn specific notes when they're ready. It's the notes themselves that I care about here, not the sources I use to make the notes.

> This project is mortii work. It all depends if he wants to implement it.

I know that I'm owed nothing. This is a humble request to add I feature that I enjoyed in Morphman. The only way to know if he wants to implement it is by asking, so I created this issue to do just that. Nothing more.

**Comment by Vilhelm-Ian** [comment] 2023-12-10 00:03
> This project is mortii work. It all depends if he wants to implement it.

I know that I'm owed nothing. This is a humble request to add a feature that I enjoyed in Morphman. The only way to know if he wants to implement it is by asking, so I created this issue to do just that. Nothing more.



My wasn't that you are not owned anything. We apreciate that you requested a feature. I wanted to say. The fact that I don't find it useful. Dosen't mean your feature won't be implemented.

**Comment by HQYang1979** [comment] 2023-12-10 03:31
Sorry to say that I don't understand the merits here. For both of the requests.

**Comment by mortii** [comment] 2023-12-10 11:53
> **Is your feature request related to a problem? Please describe.** I like to see how close a note is to being ready. It helps to give me motivation when I see more and more cards start to have lower unknown counts, and it lets me know how close I am to being able to learn specific notes.
> 
> **Describe the solution you'd like** Add an optional field in the "Extra Fields" section that's similar to the one Morphman has. Maybe call it something like "AM_unknown_count". If not that, then add some other way of seeing the number of unknown morphs on a note.
> 
> **Describe alternatives you've considered** N/A
> 
> **Additional context** Morphman has a field for this, and I liked it.

@buster-blue Thank you for the suggestion! I love seeing new people get involved with shaping the project :)

I always thought that option in MorphMan was pretty redundant since you could just look at the focus morphs and count them, but I never thought about the use case you described--sorting on the field in the browser could be useful.

> Also for the motivation part. I get I also liked seeing unknown morphs part on the readability analyzer go down.
> I just don't think there is a valid reason to add this feature.

@Vilhelm-Ian I disagree with this. The add-on is meant to make language learning easier -> learning is easier if you are more motivated -> features that increase motivation are therefore valid.

Adding this will be pretty easy, so I will do it sometime in the near future!

**Comment by buster-blue** [comment] 2023-12-10 13:03
> You alrady mentioned motivation. But why does it intrest you.

Well aside from motivation, one more thing I would do sometimes is sort the cards to find the ones with the highest morphs, then check if I have other sentences with those morphs, so that I know that I'll be able to get those notes down to single-target, and if not I try to do something about it.

>couldn't you just manually count the number of unknown morphs in the unknown field

Yes, but this means that I can't sort, so I have to manually look at each card, which would take an unreasonable amount of time when I have a little under 1000 new cards currently. Being able to sort makes it quick and easy. 



> Adding this will be pretty easy, so I will do it sometime in the near future!

Great to hear! Thanks!

**Comment by HQYang1979** [comment] 2023-12-10 13:06
> Well aside from motivation, one more thing I would do sometimes is sort the cards to find the ones with the highest morphs, then check if I have other sentences with those morphs, so that I know that I'll be able to get those notes down to single-target, and if not I try to do something about it.

I understand now.

**Comment by mortii** [comment] 2023-12-11 11:26
> I want to see how close a note is to being ready, by seeing how many unknown morphs it has, and to be able to sort all the notes by how many unknowns they have to compare using field sorting.

@buster-blue could you provide the steps you do to accomplish this? I want to make sure I can reproduce it.

**Comment by buster-blue** [comment] 2023-12-11 13:38
@mortii Sure. So basically I just added this field as one of the optional fields with Morphman that you could add, then when I would look at the cards, I'd have the "unknown morph count" field expanded by default, so I could see them. And when I'd want to sort by the field to compare them, I'd go to the browse page, and set that field as the sort field. It requires a full sync every time you do it which is annoying, but it does actually work, and it helps me see which notes are close to being ready, and which are far.

**Comment by mortii** [comment] 2023-12-11 14:09
> when I'd want to sort by the field to compare them, I'd go to the browse page, and set that field as the sort field

@buster-blue how do you do this part?

**Comment by mortii** [comment] 2023-12-11 14:29
![Screenshot from 2023-12-11 15-27-36](https://github.com/mortii/anki-morphs/assets/15674619/91780cf7-07c1-451c-b3e6-3362eaac5432)

What should the column header be? 'Number of unknowns' is a little lengthy, but that is fine i guess.

**Comment by Vilhelm-Ian** [comment] 2023-12-11 14:59
> @Vilhelm-Ian I disagree with this. The add-on is meant to make language learning easier -> learning is easier if you are more motivated -> features that increase motivation are therefore valid.

I get that. But I don't get why he finds it motivating

**Comment by mortii** [comment] 2023-12-11 15:12
> I get that. But I don't get why he finds it motivating

It's just a different way of seeing progress in your card collection. 

> I get I also liked seeing unknown morphs part on the readability analyzer go down

It is just a transformed version of this.

**Comment by mortii** [comment] 2023-12-11 15:38
> "Number of Unknowns" works okay. For something shorter, "Unknown Count" is probably clear too.

@buster-blue It might just be an idiosyncrasy I have, but when I see 'unkowns count' it is not immediately understandable to me what it does, it takes me a couple of nano seconds to decipher it. 

I added some other potential phrases:

![Screenshot from 2023-12-11 16-29-04](https://github.com/mortii/anki-morphs/assets/15674619/9ad4a1cd-83c6-48da-a8e1-7e2680da1b01)

How do you feel about '# of Unknowns'? I 'm not sure I like that any better though..

**Comment by buster-blue** [comment] 2023-12-11 17:30
@mortii "# of Unknowns" is also okay. I find myself reading it as "ID of unknowns" at first for some reason, but it is the number sign so that's probably just me. "Unknowns sum" also works and I don't think it can be confused for anything.

**Comment by mortii** [comment] 2023-12-12 11:02
> @mortii "# of Unknowns" is also okay. I find myself reading it as "ID of unknowns" at first for some reason, but it is the number sign so that's probably just me. "Unknowns sum" also works and I don't think it can be confused for anything.

@buster-blue you're right, the # sign is very ambiguous. I'll just use 'Unknowns Count', I can't think of anything better.

**Comment by mortii** [comment] 2023-12-12 13:49
The update is now live! Thanks for teaching me about the sorting option @buster-blue, it's super cool :)

**Closed by mortii** 2023-12-12 13:49 UTC
Labels: enhancement
