### ISSUE TITLE
changing notetype produces strange results

### ISSUE THREAD

**Issue by fuquasteve** [mortii/anki-morphs#208] opened 2024-04-04 18:05 UTC
### Describe the bug

I messed my ankimorphs deck up a bunch.  I don't know if this would be considered a bug, or if it is just something that should be warned about, perhaps in the documentation.

I changed the order of the fields in my notetype.
When I did a recalc, the results were strange, and clearly incorrect.
I suspect that I should have just made a new row for my modified notetype and then things would have just worded.

### Expected behavior

ankimorphs should have read the fields in the changed order and produced logical results.

### Screenshots

[//]: # (If applicable, add screenshots to help explain your problem, otherwise you can delete this section.)

### My setup

[//]: # (Note: the AnkiMorphs version is found on the bottom of the AnkiMorphs settings window)

[//]: # (Example:)
[//]: # (- Operating System: Windows 11)
[//]: # (- Anki Version: 23.12.1)
[//]: # (- AnkiMorphs Version: v2.0.0)

 - Operating System:Linux (Manjaro)
 - Anki Version:Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.11.8 Qt 6.6.2 PyQt 6.6.1
 - AnkiMorphs Version:2.2.0

### Additional context

My deck I am analyzing and modifying with ankimorphs is ridiculously big, 309 000 cards, if this effects anything.

Perhaps this should just be a warning in the documentation, or moving the warning I didn't find to a more prominent position

I set off a cascade of errors with my attempts to correct this problem.  There was an easy fix that I finally figured out.  I will submit a simple enhancement request that I wish I had had.

**Comment by mortii** [comment] 2024-04-04 18:16
Oh wow, that is really, really bad. 

This is caused by the settings saving the index of the field instead of always looking it up based on the name/title. I'll fix it asap!

> There was an easy fix that I finally figured out. I will submit a simple enhancement request that I wish I had had.

One easy fix right now would be to just save the note filter settings again after you have finished changing the fields of your cards, that way the field index is correct again.

**Comment by mortii** [comment] 2024-04-05 10:08
I'm going to do this:
- [ ] add a `(none)` option to the QComboBoxes in the settings:
    - [ ] note type
    - [ ] field
    - [ ] morphemizer
    - [ ] morph priority
- [ ] set the default options to `(none)`
- [ ] set the options to `(none)` if the stored option is no longer found
- [ ] don't store the index of the selected options
- [ ] dynamically find the indices on recalc
- [ ] abort recalc if indices are not found
- [ ] abort recalc if `(none)` is found

**Comment by mortii** [comment] 2024-04-12 20:03
@fuquasteve should be fixed in [v2.2.3](https://github.com/mortii/anki-morphs/releases/tag/v2.2.3).

Thanks!

**Closed by mortii** 2024-04-12 20:03 UTC
Labels: bug
